---
docker_packages_base:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - http://vault.centos.org/centos/7.6.1810/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
docker_package: >-
    docker-ce{{ (docker_version != 'latest') | ternary('-' ~ docker_version ~ '*', '') }}

docker_repo_default: https://download.docker.com/linux/centos/7/$basearch/stable
docker_gpg_default: https://download.docker.com/linux/centos/gpg
