---
docker_packages_base:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - container-selinux
docker_package: >-
    docker-ce{{ (docker_version != 'latest') | ternary('-' ~ docker_version ~ '*', '') }}

docker_repo_default: https://download.docker.com/linux/centos/7/$basearch/stable
docker_gpg_default: https://download.docker.com/linux/centos/gpg
