---
docker_packages_base:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
docker_package: >-
    docker-ce{{ (docker_version != 'latest') | ternary('=' ~ docker_version ~ '*', '') }}

docker_repo_default: >-
      deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
docker_gpg_default: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
