---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: centos:7
    command: "/usr/sbin/init"
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
