---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: "docker - check Docker package status"
      package:
        name: "docker-ce"
        state: "installed"
      check_mode: yes
      register: pkg_status
 
    - name: "docker - test docker package is installed"
      assert:
        that:
          - not pkg_status.changed
  
    - name: "docker - check docker service status"
      service:
        name: "docker"
        state: "started"
        enabled: "yes"
      check_mode: yes
      register: svc_status
  
    - name: "docker - test docker service is started and enabled"
      assert:
        that:
          - not svc_status.changed
